<table>
    <thead>
        <tr>
            <th>Username</th>
            <th>Password</th>
            <th>Kelas</th>
            <th>Nama Wali Murid</th>
            <th>Ponsel</th>
            <th>Surel</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    </tbody>
</table>